SELECT
  InvoiceID as Id,
  {{{temporal_fields}}},
  CAST(JSON_VALUE(Contact.ContactID) as STRING) as ContactID,
  InvoiceNumber,
  Date as InvoiceDate,
  Reference,
  DueDate,
  (Type = 'ACCREC') as IsAccRec,
  (Type = 'ACCPAY') as IsAccPay,
  (Status = 'DRAFT') as IsDraft,
  (Status = 'AUTHORISED') as IsAuthorised,
  (Status = 'PAID') as IsPaid,
  (Status = 'VOIDED') as IsVoided,
  (Status = 'DELETED') as IsDeleted,
  SubTotal,
  TotalTax,
  TotalDiscount,
  Total,
  AmountPaid,
  AmountCredited,
  SentToContact,
  FullyPaidOnDate,
  PlannedPaymentDate,
  ExpectedPaymentDate,  
  null as CreatedAt,
  UpdatedDateUTC as UpdatedAt
  FROM {{invoices}}
