module.exports = {
  0: require('./api/produce'),
  1: require('./api/fetch'),
  2: require('./api/list-offsets'),
  3: require('./api/metadata'),
  // LeaderAndIsr: 4,
  // StopReplica: 5,
  // UpdateMetadata: 6,
  // ControlledShutdown: 7,
  8: require('./api/offset-commit'),
  9: require('./api/offset-fetch'),
  10: require('./api/group-coordinator'),
  11: require('./api/join-group'),
  12: require('./api/heartbeat'),
  13: require('./api/leave-group'),
  14: require('./api/sync-group'),
  // DescribeGroups: 15,
  // ListGroups: 16,
  // SaslHandshake: 17,
  18: require('./api/api-versions'),
  19: require('./api/create-topics')
  // DeleteTopics: 20,
  // DeleteRecords: 21,
  // InitProducerId: 22,
  // OffsetForLeaderEpoch: 23,
  // AddPartitionsToTxn: 24,
  // AddOffsetsToTxn: 25,
  // EndTxn: 26,
  // WriteTxnMarkers: 27,
  // TxnOffsetCommit: 28,
  // DescribeAcls: 29,
  // CreateAcls: 30,
  // DeleteAcls: 31,
  // DescribeConfigs: 32,
  // AlterConfigs: 33, // ApiVersions v0 and v1 on Kafka 0.11
  // AlterReplicaLogDirs: 34,
  // DescribeLogDirs: 35,
  // SaslAuthenticate: 36,
  // CreatePartitions: 37,
  // CreateDelegationToken: 38,
  // RenewDelegationToken: 39,
  // ExpireDelegationToken: 40,
  // DescribeDelegationToken: 41,
  // DeleteGroups: 42, // ApiVersions v2 on Kafka 1.0
  // ElectPreferredLeaders: 43,
}
