'use strict'

module.exports = {
  NONE: 0,
  OFFSET_OUT_OF_RANGE: 1,
  UNKNOWN_TOPIC_OR_PARTITION: 3,
  INVALID_GROUP_ID: 24,
  UNKNOWN_MEMBER_ID: 25,
  REBALANCE_IN_PROGRESS: 27,
  UNSUPPORTED_VERSION: 35,
  TOPIC_ALREADY_EXISTS: 36,
  INVALID_REQUEST: 42
}
