module.exports = {
  testRegex: '^$',
  projects: [
    '<rootDir>/apps/client',
    '<rootDir>/apps/client-e2e',
    '<rootDir>/apps/backend',
    '<rootDir>/libs/language',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/editor',
    '<rootDir>/libs/fnqueue',
    '<rootDir>/libs/docsync',
    '<rootDir>/libs/dynamodb-lock',
    '<rootDir>/libs/queries',
    '<rootDir>/libs/testutils',
    '<rootDir>/libs/services',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/react-utils',
    '<rootDir>/libs/backend-test-sandbox',
    '<rootDir>/libs/sync-connection-lambdas',
    '<rootDir>/libs/slate-yjs',
  ],
};
