import { Computer } from '../computer';
import { testBlocks } from '../testUtils';
import { findNames } from './findNames';

it('finds names', async () => {
  const blocks = testBlocks(
    `This_name_was_autogenerated = "Do not show in autocomplete"`,
    `Table1 = { Hello = ["World"] }`,
    `Table1.Column2 = [1]`,
    `f(x) = x + 1`
  );

  const computer = new Computer();
  await computer.computeRequest({
    program: blocks.map((block) => ({
      type: 'identified-block',
      id: block.id,
      block,
      source: '',
    })),
  });

  expect([
    ...findNames(
      computer.computationRealm,
      blocks,
      new Set(['This_name_was_autogenerated'])
    ),
  ]).toMatchInlineSnapshot(`
    Array [
      Object {
        "blockId": "block-1",
        "kind": "variable",
        "name": "Table1",
        "type": Object {
          "columnNames": Array [
            "Hello",
          ],
          "columnTypes": Array [
            Object {
              "kind": "string",
            },
          ],
          "indexName": "Table1",
          "kind": "table",
        },
      },
      Object {
        "isLocal": false,
        "kind": "column",
        "name": "Table1.Hello",
        "type": Object {
          "cellType": Object {
            "kind": "string",
          },
          "columnSize": "unknown",
          "indexedBy": "Table1",
          "kind": "column",
        },
      },
      Object {
        "isLocal": false,
        "kind": "column",
        "name": "Table1.Column2",
        "type": Object {
          "cellType": Object {
            "kind": "number",
            "unit": null,
          },
          "columnSize": "unknown",
          "indexedBy": "Table1",
          "kind": "column",
        },
      },
      Object {
        "blockId": "block-3",
        "kind": "function",
        "name": "f",
        "type": Object {
          "argCount": 1,
          "ast": null,
          "kind": "function",
          "name": "f",
        },
      },
    ]
  `);
});
