import { it, expect } from 'vitest';
import { parseFunctionSignature, parseType } from './parseType';

it('creates primitives', () => {
  expect(parseType('number')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": "number",
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('string')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": "string",
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('boolean')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": "boolean",
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
});

it('creates columns', () => {
  expect(parseType('column<number>')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": false,
        "atParentIndex": null,
        "cellType": null,
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": null,
        "tree": undefined,
        "type": "number",
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('column<column<number>>')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": false,
        "atParentIndex": null,
        "cellType": Type {
          "anythingness": false,
          "atParentIndex": null,
          "cellType": null,
          "columnNames": null,
          "columnTypes": null,
          "date": null,
          "delegatesIndexTo": undefined,
          "errorCause": null,
          "functionArgNames": undefined,
          "functionBody": undefined,
          "functionName": undefined,
          "functionScopeDepth": undefined,
          "functionness": false,
          "indexName": null,
          "indexedBy": null,
          "node": null,
          "nothingness": false,
          "numberError": null,
          "numberFormat": null,
          "pending": false,
          "rangeOf": null,
          "rowCellNames": null,
          "rowCellTypes": null,
          "rowCount": undefined,
          "rowIndexName": null,
          "symbol": null,
          "tree": undefined,
          "type": "number",
          "unit": null,
          Symbol(immer-draftable): true,
        },
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": null,
        "tree": undefined,
        "type": null,
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('column<number>')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": false,
        "atParentIndex": null,
        "cellType": null,
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": null,
        "tree": undefined,
        "type": "number",
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('column<number>')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": false,
        "atParentIndex": null,
        "cellType": null,
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": null,
        "tree": undefined,
        "type": "number",
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
});

it('constructs anything', () => {
  expect(parseType('anything')).toMatchInlineSnapshot(`
    Type {
      "anythingness": true,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('column<anything>')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": true,
        "atParentIndex": null,
        "cellType": null,
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": null,
        "tree": undefined,
        "type": null,
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
});

it('understands symbols', () => {
  expect(parseType('number:A')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": "A",
      "tree": undefined,
      "type": "number",
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('column<anything:A>')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": true,
        "atParentIndex": null,
        "cellType": null,
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": "A",
        "tree": undefined,
        "type": null,
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('column<anything>:A')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": Type {
        "anythingness": true,
        "atParentIndex": null,
        "cellType": null,
        "columnNames": null,
        "columnTypes": null,
        "date": null,
        "delegatesIndexTo": undefined,
        "errorCause": null,
        "functionArgNames": undefined,
        "functionBody": undefined,
        "functionName": undefined,
        "functionScopeDepth": undefined,
        "functionness": false,
        "indexName": null,
        "indexedBy": null,
        "node": null,
        "nothingness": false,
        "numberError": null,
        "numberFormat": null,
        "pending": false,
        "rangeOf": null,
        "rowCellNames": null,
        "rowCellTypes": null,
        "rowCount": undefined,
        "rowIndexName": null,
        "symbol": null,
        "tree": undefined,
        "type": null,
        "unit": null,
        Symbol(immer-draftable): true,
      },
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": "A",
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('A')).toMatchInlineSnapshot(`
    Type {
      "anythingness": true,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": "A",
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
});

it('understands nothing and anything', () => {
  expect(parseType('anything')).toMatchInlineSnapshot(`
    Type {
      "anythingness": true,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": false,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
  expect(parseType('nothing')).toMatchInlineSnapshot(`
    Type {
      "anythingness": false,
      "atParentIndex": null,
      "cellType": null,
      "columnNames": null,
      "columnTypes": null,
      "date": null,
      "delegatesIndexTo": undefined,
      "errorCause": null,
      "functionArgNames": undefined,
      "functionBody": undefined,
      "functionName": undefined,
      "functionScopeDepth": undefined,
      "functionness": false,
      "indexName": null,
      "indexedBy": null,
      "node": null,
      "nothingness": true,
      "numberError": null,
      "numberFormat": null,
      "pending": false,
      "rangeOf": null,
      "rowCellNames": null,
      "rowCellTypes": null,
      "rowCount": undefined,
      "rowIndexName": null,
      "symbol": null,
      "tree": undefined,
      "type": null,
      "unit": null,
      Symbol(immer-draftable): true,
    }
  `);
});

it('parses function sigs', () => {
  expect(parseFunctionSignature('number, number -> boolean'))
    .toMatchInlineSnapshot(`
      {
        "expectedArgs": [
          Type {
            "anythingness": false,
            "atParentIndex": null,
            "cellType": null,
            "columnNames": null,
            "columnTypes": null,
            "date": null,
            "delegatesIndexTo": undefined,
            "errorCause": null,
            "functionArgNames": undefined,
            "functionBody": undefined,
            "functionName": undefined,
            "functionScopeDepth": undefined,
            "functionness": false,
            "indexName": null,
            "indexedBy": null,
            "node": null,
            "nothingness": false,
            "numberError": null,
            "numberFormat": null,
            "pending": false,
            "rangeOf": null,
            "rowCellNames": null,
            "rowCellTypes": null,
            "rowCount": undefined,
            "rowIndexName": null,
            "symbol": null,
            "tree": undefined,
            "type": "number",
            "unit": null,
            Symbol(immer-draftable): true,
          },
          Type {
            "anythingness": false,
            "atParentIndex": null,
            "cellType": null,
            "columnNames": null,
            "columnTypes": null,
            "date": null,
            "delegatesIndexTo": undefined,
            "errorCause": null,
            "functionArgNames": undefined,
            "functionBody": undefined,
            "functionName": undefined,
            "functionScopeDepth": undefined,
            "functionness": false,
            "indexName": null,
            "indexedBy": null,
            "node": null,
            "nothingness": false,
            "numberError": null,
            "numberFormat": null,
            "pending": false,
            "rangeOf": null,
            "rowCellNames": null,
            "rowCellTypes": null,
            "rowCount": undefined,
            "rowIndexName": null,
            "symbol": null,
            "tree": undefined,
            "type": "number",
            "unit": null,
            Symbol(immer-draftable): true,
          },
        ],
        "returnType": Type {
          "anythingness": false,
          "atParentIndex": null,
          "cellType": null,
          "columnNames": null,
          "columnTypes": null,
          "date": null,
          "delegatesIndexTo": undefined,
          "errorCause": null,
          "functionArgNames": undefined,
          "functionBody": undefined,
          "functionName": undefined,
          "functionScopeDepth": undefined,
          "functionness": false,
          "indexName": null,
          "indexedBy": null,
          "node": null,
          "nothingness": false,
          "numberError": null,
          "numberFormat": null,
          "pending": false,
          "rangeOf": null,
          "rowCellNames": null,
          "rowCellTypes": null,
          "rowCount": undefined,
          "rowIndexName": null,
          "symbol": null,
          "tree": undefined,
          "type": "boolean",
          "unit": null,
          Symbol(immer-draftable): true,
        },
      }
    `);
});

it('errors', () => {
  expect(() => parseType('number number')).toThrow(/garbage at the end/);

  expect(() => parseType('column<number x')).toThrow(/expected gt/);

  expect(() => parseType('>')).toThrow(/unexpected/);

  expect(() => parseType('column<number, A>')).toThrow(/expected/);
});
