import {
  ELEMENT_BLOCKQUOTE,
  ELEMENT_CALLOUT,
  ELEMENT_DISPLAY,
  ELEMENT_IFRAME,
  ELEMENT_IMAGE,
  ELEMENT_PARAGRAPH,
  ELEMENT_VARIABLE_DEF,
} from './element-kinds';

export const COLUMN_KINDS = [
  ELEMENT_VARIABLE_DEF,
  ELEMENT_DISPLAY,
  ELEMENT_BLOCKQUOTE,
  ELEMENT_IMAGE,
  ELEMENT_PARAGRAPH,
  ELEMENT_CALLOUT,
  ELEMENT_IFRAME,
];
