/* eslint-disable no-await-in-loop */
import pSeries from 'p-series';
import { Writable } from 'utility-types';
import { AST } from '..';
import {
  InferError,
  Type,
  buildType as t,
  deserializeType,
  typeIsPending,
} from '../type';
import { matchUnitArraysForColumn } from '../type/units';
import { getDefined, getIdentifierString } from '../utils';
import { getDateFromAstForm } from '../date';
import { expandDirectiveToType } from '../directives';
import { parseUnit } from '../units';
import { inferTable } from '../tables/inference';
import { inferColumnAssign } from '../tables/column-assign';

import { Context, makeContext, logRetrievedName } from './context';
import { inferSequence } from './sequence';
import { isPreviousRef } from '../previous-ref';
import { inferMatrixAssign, inferMatrixRef } from '../matrix';
import { inferCategories } from '../categories';
import { inferFunctionDefinition, inferFunctionCall } from './functions';
import { getConstantByName } from '../builtins';
import { inferMatch } from '../match/inferMatch';
import { inferTiered } from '../tiered/inferTiered';
import { sortType } from './sortType';

export { makeContext, logRetrievedName };
export type { Context };
export type { ContextStats } from './inferStats';
export { initialInferStats } from './inferStats';

export const linkToAST = (node: Writable<AST.Node>, type: Type) => {
  node.inferredType = type;

  if (type.errorCause != null && type.node == null) {
    return type.inNode(node);
  } else {
    return type;
  }
};

const wrap =
  <T extends AST.Node>(
    fn: (ctx: Context, node: T, cohercingTo?: Type) => Promise<Type>
  ) =>
  async (ctx: Context, node: T, cohercingTo?: Type): Promise<Type> => {
    let type = await fn(ctx, node);
    if (cohercingTo) {
      type = await type.sameAs(cohercingTo);
    }
    return linkToAST(node, type);
  };

/**
 Walk depth-first into an expanded AST.Expression, collecting the type of things beneath and checking it against the current iteration's constraints.

 Given a literal, this type is always known (barring casting).
 Given a function call, this type is given by calling the functor with the arguments' types.
 Given a condition, the functor is (thentype == elsetype) and its condition must be boolean

 AST.Assign is special-cased by looking at its expression and returning just that
*/
export const inferExpression = wrap(
  // exhaustive switch
  // eslint-disable-next-line consistent-return
  async (ctx: Context, expr: Writable<AST.Expression>): Promise<Type> => {
    ctx.incrementStatsCounter('inferExpressionCount');
    switch (expr.type) {
      case 'noop': {
        return t.nothing();
      }
      case 'ref': {
        const name = getIdentifierString(expr);
        if (isPreviousRef(name)) {
          return (
            (ctx.previousStatement && deserializeType(ctx.previousStatement)) ||
            t.impossible(InferError.noPreviousStatement())
          );
        }
        const c = getConstantByName(name);
        if (c) {
          return c.type;
        }

        const fromStack = ctx.stack.get(name);
        if (fromStack) {
          logRetrievedName(ctx, name);
          return sortType(fromStack);
        }

        // create a unit with the name of the ref
        return ctx.autoGeneratedVarNames.has(name)
          ? t.impossible(
              new InferError({ errType: 'unknown-reference', refName: name }),
              expr
            )
          : t.number([parseUnit(name)]); // defaults to a unit with the ref name
      }
      case 'externalref': {
        const [id] = expr.args;
        const data = ctx.externalData.get(id);
        if (data) {
          return deserializeType(data.type);
        }
        return t.impossible(
          new InferError({ errType: 'unknown-reference', refName: id }),
          expr
        );
      }
      case 'literal': {
        const [litType] = expr.args;

        if (litType === 'number') {
          return t.number(null, expr.args[2]);
        }

        return t[litType]();
      }
      case 'range': {
        const [start, end] = await pSeries(
          expr.args.map(
            (expr) => async () => inferExpression(ctx, getDefined(expr))
          )
        );
        const pending = [start, end].find(typeIsPending);
        if (pending) {
          return pending;
        }

        return (await Type.combine(start, end)).mapType(async () => {
          const rangeOf = await (start.date != null
            ? start.sameAs(end)
            : (await start.isScalar('number')).sameAs(end));

          return t.range(rangeOf);
        });
      }
      case 'sequence': {
        return inferSequence(ctx, expr, inferExpression);
      }
      case 'date': {
        const [, specificity] = getDateFromAstForm(expr.args);
        return t.date(specificity);
      }
      case 'column': {
        const [columnItems, optionalIndex] = expr.args;
        if (columnItems.args.length === 0) {
          return t.impossible(InferError.unexpectedEmptyColumn());
        }
        const [firstCellNode, ...restCellNodes] = columnItems.args;
        const firstCellType = await inferExpression(ctx, firstCellNode);
        const restCellTypes = await pSeries(
          restCellNodes.map(
            (a) => async () => inferExpression(ctx, a, firstCellType)
          )
        );

        // pending type is contagious
        const pending = [firstCellType, ...restCellTypes].find(typeIsPending);
        if (pending) {
          return pending;
        }

        const erroredCell = [firstCellType, ...restCellTypes].find(
          (cell) => cell.errorCause != null
        );
        if (erroredCell != null) return erroredCell;

        for (const restCell of restCellTypes) {
          if (
            !matchUnitArraysForColumn(
              (await firstCellType.reducedToLowest()).unit,
              (await restCell.reducedToLowest()).unit
            )
          ) {
            return t.impossible(
              InferError.columnContainsInconsistentType(firstCellType, restCell)
            );
          }
        }
        return t.column(firstCellType, optionalIndex?.args[0]);
      }
      case 'property-access': {
        const [thing, prop] = expr.args;
        const propName = getIdentifierString(prop);
        const potentialTable = await inferExpression(ctx, thing);
        // pending is contagious
        if (potentialTable.pending) {
          return potentialTable;
        }
        const table = await potentialTable.isTableOrRow();

        const tableName =
          thing.type === 'ref' ? thing.args[0] : table.indexName;

        const getFromTableOrRow = (
          names: string[],
          types: Type[]
        ): [Type, number] => {
          const index = names.indexOf(propName);
          if (index < 0) {
            return [
              t.impossible(
                `A column named ${propName} does not exist in ${tableName}`
              ),
              index,
            ];
          }

          const originTable = table.indexName || table.rowIndexName;
          if (originTable) {
            logRetrievedName(ctx, [originTable, propName]);
          }
          return [types[index], index];
        };

        if (table.errorCause) {
          return table;
        } else if (table.columnNames != null && table.columnTypes != null) {
          const [column, columnIndex] = getFromTableOrRow(
            table.columnNames,
            table.columnTypes
          );
          return t.column(column, table.indexName, columnIndex);
        } else {
          const { rowCellNames, rowCellTypes } = table;
          const [type] = getFromTableOrRow(
            getDefined(rowCellNames),
            getDefined(rowCellTypes)
          );
          return type;
        }
      }
      case 'matrix-ref': {
        return inferMatrixRef(ctx, expr);
      }
      case 'function-call': {
        return inferFunctionCall(ctx, expr);
      }
      case 'directive': {
        return expandDirectiveToType(ctx, expr);
      }
      case 'match':
        return inferMatch(ctx, expr);
      case 'tiered':
        return inferTiered(ctx, expr);
    }
  }
);

const inferStatementInternal = wrap(
  async (
    /* Mutable! */ ctx: Context,
    statement: AST.Statement
  ): Promise<Type> => {
    ctx.incrementStatsCounter('inferStatementCount');
    switch (statement.type) {
      case 'assign': {
        const [nName, nValue] = statement.args;

        const varName = getIdentifierString(nName);

        const constant = getConstantByName(varName);
        const type =
          constant || ctx.stack.has(varName, 'function')
            ? t.impossible(InferError.duplicatedName(varName))
            : await inferExpression(ctx, nValue);

        ctx.stack.set(varName, type, 'function', ctx.statementId);
        return type;
      }
      case 'table': {
        return inferTable(ctx, statement);
      }
      case 'table-column-assign': {
        return inferColumnAssign(ctx, statement);
      }
      case 'matrix-assign': {
        return inferMatrixAssign(ctx, statement);
      }
      case 'categories': {
        return inferCategories(ctx, statement);
      }
      case 'function-definition': {
        return inferFunctionDefinition(ctx, statement);
      }
      default: {
        return inferExpression(ctx, statement);
      }
    }
  }
);

export const inferStatement = async (
  ...args: Parameters<typeof inferStatementInternal>
): Promise<Type> => {
  const [ctx] = args;
  const { usedNames: previoususedNames } = ctx;

  if (previoususedNames == null) {
    return inferStatementInternal(...args);
  }

  // Do not keep track of names retrieved here if we errored out
  ctx.usedNames = [...previoususedNames];

  const type = await inferStatementInternal(...args);

  if (type.errorCause) {
    ctx.usedNames = previoususedNames;
  }

  return type;
};

export const inferBlock = async (
  block: AST.Block,
  ctx = makeContext()
): Promise<Type> => {
  let last: Type | undefined;
  for (const stmt of block.args) {
    // eslint-disable-next-line no-await-in-loop
    last = await inferStatement(ctx, stmt);
  }
  return getDefined(last, 'Unexpected empty block');
};

export const inferProgram = async (
  program: AST.Block[],
  ctx = makeContext()
): Promise<Context> => {
  const start = Date.now();
  for (const block of program) {
    // eslint-disable-next-line no-await-in-loop
    await inferBlock(block, ctx);
  }
  const elapsed = Date.now() - start;
  ctx.incrementStatsCounter('totalInferProgramTimeMs', elapsed);
  return ctx;
};
