// these are the values that are good for the development sandbox
// there are no important secrets here, so you can relax.
// we need this to be JS because of our build script, which injects default
// values into the builkd targets.
const defaultEnvValues = {
  APP_ROOT_PATH: '/',
  AWS_REGION: 'eu-west-2',

  DECI_FROM_EMAIL_ADDRESS: 'Decipad<info@decipad.com>',
  DECI_APP_URL_BASE: 'http://localhost:3000',
  DECI_PORT: '3000',

  DECI_S3_ENDPOINT: 'localhost:4568',
  DECI_S3_ACCESS_KEY_ID: 'S3RVER',
  DECI_S3_SECRET_ACCESS_KEY: 'S3RVER',
  DECI_S3_PADS_BUCKET: 'pads',
  DECI_S3_PAD_BACKUPS_BUCKET: 'padBackups',
  DECI_S3_ATTACHMENTS_BUCKET: 'attachments',
  DECI_S3_THIRD_PARTIES_BUCKET: 'decipad-staging-third-parties',

  DECI_S3_EXTERNAL_DATA_SNAPSHOT_BUCKET: 'external-data-snapshot-bucket',

  DECI_INVITE_EXPIRATION_SECONDS: '604800',

  DECI_KEY_VALIDATION_EXPIRATION_SECONDS: '2592000',

  DECI_MAX_ATTACHMENT_SIZE: '10000000',

  DECI_MAX_ATTACHMENT_UPLOAD_TOKEN_EXPIRATION_SECONDS: '300',
  DECI_MAX_ATTACHMENT_DOWNLOAD_TOKEN_EXPIRATION_SECONDS: '300',

  // Third-party auth:
  DECI_DEFAULT_TOKEN_EXPIRATION_SECONDS: (365 * 60 * 60 * 24).toString(), // one year,
  DECI_GOOGLESHEETS_API_KEY: 'YOUR_GOOGLE_SHEETS_API_KEY',
  DECI_GOOGLESHEETS_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID',
  DECI_GOOGLESHEETS_CLIENT_SECRET: 'YOUR_GOOGLE_CLIENT_SECRET',

  JWT_MAX_AGE: '2592000', // 1 month (30 * 24 * 60 * 60)
  JWT_SECRET: 'YOUR_JWT_SECRET',

  OPENAI_API_KEY: 'ask the dev team',
  GOOGLE_VERTEX_API_KEY: 'ask the dev team',
  DEEPINFRA_API_KEY: 'ask the dev team',
  GIPHY_API_KEY: 'ask the dev team',
  UNSPLASH_API_KEY: 'ask the dev team',
  REPLICATE_API_KEY: 'ask the dev team',

  NEXTAUTH_URL: 'http://localhost:3000/api/auth',

  SENTRY_DSN: '',

  DISCORD_PUBLIC_KEY: 'YOUR_DISCORD_PUBLIC_KEY',
  DISCORD_APP_ID: 'YOUR_DISCORD_APP_ID',

  VITE_ANALYTICS_WRITE_KEY: '',
  VITE_POSTHOG_API_KEY: '',
  VITE_GOOGLE_ANALYTICS_ID: '',

  // Tests-related
  DECI_TEST_USER_SECRET: 'YOUR_TEST_USER_SECRET',

  INTERCOM_SECRET_ID: '',

  STRIPE_WEBHOOK_SECRET: 'whsec_YOUR_STRIPE_WEBHOOK_SECRET',
  STRIPE_API_KEY: 'pk_test_YOUR_STRIPE_PUBLISHABLE_KEY',
  STRIPE_SECRET_KEY: 'sk_test_YOUR_STRIPE_SECRET_KEY',
  STRIPE_EXTRA_CREDITS_PRODUCT_ID: 'prod_YOUR_EXTRA_CREDITS_PRODUCT_ID',
  STRIPE_SUBSCRIPTIONS_PRODUCT_ID: 'prod_YOUR_SUBSCRIPTIONS_PRODUCT_ID',
  VITE_STRIPE_CUSTOMER_PORTAL_LINK:
    'https://billing.stripe.com/p/login/YOUR_CUSTOMER_PORTAL_LINK',

  NOTION_CLIENT_ID: 'use .env',
  NOTION_CLIENT_SECRET: 'use .env',
  // Internal AI feedback
  DISCORD_FEEDBACK_CHANNEL_TOKEN: 'YOUR_DISCORD_FEEDBACK_CHANNEL_TOKEN',
  DISCORD_FEEDBACK_CHANNEL_ID: 'YOUR_DISCORD_FEEDBACK_CHANNEL_ID',
  DECI_MAX_QUERIES_FREE: '10',
  DECI_MAX_QUERIES_PRO: '500',
  DECI_MAX_CREDITS_FREE: '50',
  DECI_MAX_CREDITS_PRO: '500',
  DECI_TOKENS_TO_CREDITS: '2000',
  DECI_MAX_COLLAB_READERS_FREE_PLAN: '3',
  WORKSPACE_FREE_PLAN: 'free',
  WORKSPACE_PRO_PLAN: 'pro',
  WORKSPACE_FREE_PLAN_NAME: 'Free',
  OPENAI_DECIPAD_GPT_BEARER_KEY: '',
  MAILERSEND_API_KEY: '',
  DATALAKE_GOOGLE_ROOT_SERVICE_CREDENTIALS: '',
  DATALAKE_WEBHOOK_SECRET: 'YOUR_DATALAKE_WEBHOOK_SECRET',
  DATALAKE_AIRBYTE_CLIENT_ID: '',
  DATALAKE_AIRBYTE_CLIENT_SECRET: '',
  DATALAKE_AIRBYTE_URL: 'http://localhost:8000',
  DATALAKE_AIRBYTE_WORKSPACE_ID: '',
};

export type SupportedEnvKey = keyof typeof defaultEnvValues;
export function defaultEnv(key: SupportedEnvKey): string {
  return defaultEnvValues[key];
}
