/* eslint-disable no-underscore-dangle */
const { join } = require('node:path');

exports.notebooks = [
  'budget-distribution.json',
  'budget-planning.json',
  'candle-business.json',
  'consulting-project-calculator.json',
  'data-consultancy.json',
  'finance-balance-tracker.json',
  'finance-tracker-2023.json',
  'github-enterprise-versus-buildjet.json',
  'guide-to-calculating-costs.json',
  'hourly-rate-calculator.json',
  'how-much-is-apple-worth.json',
  'interactive-pricing-proposals.json',
  'investment-portfolio.json',
  'lemonade-stand-business-model.json',
  'micro-brewery-financial-model.json',
  'monthly-investor-update.json',
  'mortgage-loan.json',
  'offer-letter-startup.json',
  'office-space-calculator.json',
  'pricing-calculator.json',
  'pricing-roi-calculator.json',
  'profit-sharing-vc-model.json',
  'real-price-social-media.json',
  'rent-your-home.json',
  'salary-negotiations.json',
  'sales-commission-plan.json',
  'sales-pipeline-monthly-report.json',
  'saving-for-big-purchase.json',
  'sdr-compensation.json',
  'simple-business-model.json',
  'simple-monthly-revenue-report.json',
  'simple-with-code.json',
  'simple-with-ui-components.json',
  'simplest.json',
  'solar-panels.json',
  'spotify-price-increase.json',
  'startup-stock-options.json',
  'tables.json',
  'trip-budget-planner.json',
  'whats-your-founder-number.json',
  'when-can-i-retire.json',
  'apple-model.json',
  'chartr1.json',
  'chartr2.json',
  'investor-update-example.json',
  'offer-letter.json',
  'performance-summary-letter.json',
  'sales-pipeline.json',
  'seed-founders.json',
  'shilling.json',
  'sprint-capacity.json',
  'stock-options-startup.json',
].map((path) => join(__dirname, '..', 'notebooks', path));
