/* eslint-disable no-underscore-dangle */
const { join } = require('node:path');

const languageDocs = [
  'docs/advanced/combinations.mdx',
  'docs/advanced/conditions.md',
  'docs/advanced/custom-function.mdx',
  'docs/advanced/intervals.md',
  'docs/advanced/lookups.md',
  'docs/advanced/units.md',
  'docs/functions-list/01-absolute-number.md',
  'docs/functions-list/02-division-remainder.md',
  'docs/functions-list/03-factorial.md',
  'docs/functions-list/04-get-number-units.md',
  'docs/functions-list/05-natural-logarithm.md',
  'docs/functions-list/06-remove-number-units.md',
  'docs/functions-list/07-round.md',
  'docs/functions-list/08-square-root.md',
  'docs/functions-list/09-trigonometric-functions.md',
  'docs/functions-list/10-average.md',
  'docs/functions-list/11-concatenate.md',
  'docs/functions-list/12-lenght.md',
  'docs/functions-list/13-count.md',
  'docs/functions-list/14-filter.md',
  'docs/functions-list/15-first.md',
  'docs/functions-list/16-grow.md',
  'docs/functions-list/17-last.md',
  'docs/functions-list/18-lookup.md',
  'docs/functions-list/19-max.md',
  'docs/functions-list/20-min.md',
  'docs/functions-list/21-previous.mdx',
  'docs/functions-list/22-reverse.md',
  'docs/functions-list/23-sort.md',
  'docs/functions-list/24-stepgrowth.md',
  'docs/functions-list/25-sum.md',
  'docs/functions-list/26-unique.md',
  'docs/functions-list/27-compound.md',
  'docs/functions-list/28-future-value.md',
  'docs/functions-list/29-net-present-value.md',
  'docs/functions-list/30-payment-amounts.md',
  'docs/functions-list/31-contains.md',
  'docs/functions-list/32-pick.md',
  'docs/functions-list/functions-list.mdx',
  'docs/quick-start/formulas.mdx',
  'language/data-types/01-variables.md',
  'language/data-types/02-strings.md',
  'language/data-types/03-dates.md',
  'language/data-types/04-columns.md',
  'language/data-types/06-booleans.md',
  'language/data-types/07-ranges.md',
  'language/data-types/08-time-intervals.md',
  'language/data-types/10-sequences.md',
  'language/modeling/05-conditions.md',
  'language/modeling/09-dimensions.md',
  'language/modeling/11-code-tables.md',
  'language/modeling/13-functions.md',
  'language/modeling/15-lookups.md',
  'language/modeling/16-previous.md',
];

exports.languageDocs = languageDocs;

exports.languageDocPath = (doc) =>
  join(__dirname, '..', '..', '..', 'apps', 'docs', doc);
