SELECT
  id as Id,
  {{{temporal_fields}}},
  name as Name,
  type as Type,
  subType as SubType,
  subject as Subject,
  appId as AppId,
  appName as AppName,
  counters_open as OpenCount,
  counters_sent as SentCount,
  counters_click as ClickCount,
  counters_print as PrintCount,
  counters_reply as ReplyCount,
  counters_bounce as BounceCount,
  counters_dropped as DroppedCount,
  counters_forward as ForwardCount,
  counters_deferred as DeferredCount,
  counters_delivered as DeliveredCount,
  counters_processed as ProcessedCount,
  counters_spamreport as SpamReportCount,
  counters_suppressed as SuppressedCount,
  counters_mta_dropped as MtaDroppedCount,
  counters_statuschange as StatusChangeCount,
  counters_unsubscribed as UnsubscribedCount,
  
  null as CreatedAt,
  lastUpdatedTime as LastUpdated,
  FROM {{campaigns}}
