SELECT
  id as Id,
  {{{temporal_fields}}},
  archived as IsArchived,

  properties_name as Name,
  properties_type as Type,
  properties_country as Country,
  properties_state as State,
  properties_industry as Industry,
  properties_numberofemployees as NumEmployees,
  properties_annualrevenue as AnnualRevenue,
  properties_total_revenue as TotalRevenue,
  properties_total_money_raised as TotalMoneyRaised,

  properties_lifecyclestage as LifecycleStage,
  properties_hs_lead_status as LeadStatus,
  properties_hs_time_in_lead as TimeInLead,
  properties_days_to_close as DaysToClose,
  properties_hs_num_open_deals as NumOpenDeals,
  properties_recent_deal_amount as RecentDealAmount,
  properties_hs_total_deal_value as TotalDealValue,
  properties_notes_last_contacted as LastContacted,
  properties_num_associated_deals as NumAssociatedDeals,
  properties_first_conversion_date as FirstConversionDate,
  properties_hs_date_entered_lead as DateEnteredLead,
  properties_hs_created_by_user_id as CreatedByUserId,
  properties_first_contact_createdate as FirstContactCreatedate,
  properties_hs_v2_date_entered_customer as DateEnteredCustomer,
  properties_hs_date_entered_opportunity as DateEnteredOpportunity,
  properties_hs_last_sales_activity_date as LastSalesActivityDate,
  properties_hs_last_sales_activity_type as LastSalesActivityType,
  properties_hs_target_account_probability as TargetAccountProbability,

  properties_engagements_last_meeting_booked as LastMeetingBooked,
  properties_hs_analytics_source as AnalyticsSource,
  properties_hs_analytics_latest_source as AnalyticsLatestSource,
  properties_hs_analytics_latest_source_timestamp as AnalyticsLatestSourceTimestamp,
  properties_hs_analytics_num_visits as AnalyticsNumVisits,
  properties_hs_analytics_num_page_views as AnalyticsNumPageviews,
  properties_hs_analytics_first_visit_timestamp as AnalyticsFirstVisitTimestamp,

  createdAt as CreatedAt,
  updatedAt as LastUpdated,
  FROM {{companies}}
