SELECT
  id as Id,
  {{{temporal_fields}}},
  archived as IsArchived,
  properties_firstname as FirstName,
  properties_lastname as LastName,
  properties_email as Email,
  properties_phone as Phone,
  properties_website as Website,
  properties_job_function as JobFunction,
  properties_company_size as CompanySize,
  properties_company as Company,
  properties_country as Country,
  properties_state as State,
  properties_industry as Industry,
  properties_numemployees as NumEmployees,
  properties_annualrevenue as AnnualRevenue,

  properties_closedate as CloseDate,
  properties_days_to_close as DaysToClose,
  properties_total_revenue as TotalRevenue,
  properties_lifecyclestage as LifecycleStage,

  properties_recent_deal_amount as RecentDealAmount,
  properties_currentlyinworkflow as CurrentlyInWorkflow,
  properties_hs_analytics_source as AnalyticsSource,
  properties_hs_marketable_status as MarketableStatus,
  properties_hs_lead_status as LeadStatus,
  properties_notes_last_contacted as LastContacted,
  properties_first_conversion_date as FirstConversionDate,
  properties_recent_conversion_date as RecentConversionDate,
  properties_hs_analytics_first_url as FirstUrl,
  properties_hs_first_outreach_date as FirstOutreachDate,
  properties_hs_registration_method as RegistrationMethod,
  properties_hs_time_in_opportunity as TimeInOpportunity,
  properties_first_deal_created_date as FirstDealCreatedDate,
  properties_recent_deal_close_date as RecentDealCloseDate,
  properties_hs_v2_date_entered_customer as DateEnteredCustomer,
  properties_hs_v2_date_entered_opportunity as DateEnteredOpportunity,
  properties_hs_last_sales_activity_date as LastSalesActivityDate,
  properties_hs_last_sales_activity_type as LastSalesActivityType,
  properties_hs_lifecyclestage_lead_date as LifecycleStageLeadDate,

  properties_hubspot_owner_id as OwnerUserId,
  properties_associatedcompanyid as AssociatedCompanyId,

  createdAt as CreatedAt,
  updatedAt as LastUpdated,
  FROM {{contacts}}
