SELECT
  CAST(id AS STRING) as Id,
  {{{temporal_fields}}},
  CAST(JSON_VALUE(client.id) as STRING) as ClientId,
  CAST(JSON_VALUE(project.id) as STRING) as ProjectId,
  CAST(JSON_VALUE(expense_category.id) as STRING) as ExpenseCategoryId,
  CAST(JSON_VALUE(user.id) as STRING) as CreatedByUserId,
  CAST(JSON_VALUE(user_assignment.id) as STRING) as UserProjectAssignmentId,
  CAST(JSON_VALUE(invoice.id) as STRING) as InvoiceId,
  units as UnitQuantity,
  total_cost as TotalCost,
  spent_date as SpentDate,
  billable as IsBillable,
  is_closed as IsClosed,
  is_locked as IsLocked,
  is_billed as IsBilled,
  created_at as CreatedAt,
  updated_at as UpdatedAt,
FROM {{expenses}}
