SELECT
  CAST(id AS STRING) as Id,
  {{{temporal_fields}}},
  number as Number,
  subject as Subject,
  issue_date as IssueDate,
  state as State,
  CAST(JSON_VALUE(client.id) as STRING) as ClientId,
  estimate as EstimateId,
  retainer as RetainerId,
  CAST(JSON_VALUE(creator.id) as STRING) as CreatedByUserId,
  period_start as PeriodStart,
  period_end as PeriodEnd,
  amount as Amount,
  due_amount as DueAmount,
  tax_amount + tax2_amount as TaxAmount,
  currency as Currency,
  due_date as DueDate,
  sent_at as SentAt,
  paid_at as PaidAt,
  closed_at as ClosedAt,
  created_at as CreatedAt,
  updated_at as UpdatedAt,
  FROM {{invoices}}
