SELECT
  CAST(id AS STRING) as Id,
  {{{temporal_fields}}},
  CAST(JSON_VALUE(user.id) as STRING) as UserId,
  CAST(JSON_VALUE(project.id) as STRING) as ProjectId,
  CAST(JSON_VALUE(task.id) as STRING) as TaskId,
  spent_date as SpentDate,
  CAST(JSON_VALUE(user_assignment.id) as STRING) as UserProjectAssignmentId,
  CAST(JSON_VALUE(client.id) as STRING) as ClientId,
  hours as Hours,
  rounded_hours as RoundedHours,
  started_time as StartedTime,
  ended_time as EndedTime,
  is_running as IsRunning,
  billable as IsBillable,
  budgeted as IsBudgeted,
  billable_rate as BillableRate,
  cost_rate as CostRate,
  is_locked as IsLocked,
  is_closed as IsClosed,
  is_billed as IsBilled,
  CAST(JSON_VALUE(invoice.id) as STRING) as InvoiceId,
  created_at as CreatedAt,
  updated_at as UpdatedAt,
  FROM {{time_entries}}
