import {
  black,
  blue100,
  blue200,
  blue300,
  blue400,
  blue500,
  blue600,
  blue700,
  blue800,
  blue900,
  brand300,
  brand400,
  brand500,
  brand600,
  brand700,
  brand800,
  brand900,
  dark100,
  dark200,
  dark300,
  dark400,
  dark500,
  dark600,
  dark700,
  grey100,
  grey200,
  grey300,
  grey400,
  grey500,
  grey600,
  grey700,
  malibu700,
  offBlack,
  offWhite,
  orange100,
  orange300,
  orange400,
  orange500,
  orange600,
  orange700,
  orange800,
  orange900,
  purple200,
  purple300,
  purple400,
  purple500,
  purple600,
  purple700,
  purple800,
  purple900,
  red100,
  red300,
  red400,
  red50,
  red500,
  red600,
  red700,
  red800,
  red900,
  teal100,
  teal200,
  teal300,
  teal400,
  teal500,
  teal600,
  teal700,
  teal800,
  teal900,
  white,
  yellow200,
  yellow300,
  yellow400,
  yellow500,
  yellow600,
  yellow700,
  yellow800,
  yellow900,
} from '../color';
import { CssVariables } from '../CssVariables';

export const theme: CssVariables = {
  theme: 'dark',
  toastOk: brand700.hex,
  toastDanger: red600.hex,
  toastWarning: yellow700.hex,

  cellDateSelected: brand500.hex,

  formulaUnitBackground: black.hex,

  errorColor: red100.hex,
  errorColorLight: red500.hex,

  borderColor: dark500.hex,
  borderHighlightColor: purple700.hex,
  borderTable: dark500.hex,

  notebookStateDangerLight: red300.hex,
  notebookStateDangerHeavy: red100.hex,

  notebookStateWarningLight: orange700.hex,
  notebookStateWarningHeavy: orange500.hex,

  notebookStateOkLight: brand800.hex,
  notebookStateOkHeavy: brand600.hex,

  notebookStateDisabledLight: grey600.hex,
  notebookStateDisabledHeavy: grey100.hex,

  backgroundColor: dark700.hex,
  tintedBackgroundColor: grey700.hex,
  iconBackgroundColor: grey500.hex,
  offColor: grey600.hex,
  spoilerColor: offWhite.hex,

  highlightColor: dark600.hex,
  strongHighlightColor: dark500.hex,
  strongerHighlightColor: dark400.hex,
  evenStrongerHighlightColor: dark300.hex,

  weakerTextColor: dark400.hex,
  weakTextColor: dark300.hex,
  normalTextColor: dark200.hex,
  strongTextColor: white.hex,

  iconColorDark: offBlack.hex,
  iconColorLight: offWhite.hex,
  thumbColor: offWhite.hex,

  tooltipBackground: dark300.hex,
  tooltipCodeBackground: offBlack.hex,

  // legacy slash command colours
  // used in other stuff for now
  weakerSlashIconColor: blue100.hex,
  weakSlashIconColor: blue200.hex,
  strongSlashIconColor: blue500.hex,

  // slash command default colors
  // overriden with setCssVar
  slashColorLight: grey700.hex,
  slashColorNormal: grey400.hex,
  slashColorHeavy: grey300.hex,

  slashColorOceanLight: blue700.hex,
  slashColorOceanNormal: blue400.hex,
  slashColorOceanHeavy: blue300.hex,

  slashColorMintLight: teal700.hex,
  slashColorMintNormal: teal400.hex,
  slashColorMintHeavy: teal300.hex,

  slashColorOrangeLight: orange700.hex,
  slashColorOrangeNormal: orange400.hex,
  slashColorOrangeHeavy: orange300.hex,

  slashColorWineLight: purple700.hex,
  slashColorWineNormal: purple400.hex,
  slashColorWineHeavy: purple300.hex,

  slashColorDaffodilLight: yellow700.hex,
  slashColorDaffodilNormal: yellow400.hex,
  slashColorDaffodilHeavy: yellow300.hex,

  buttonPrimaryText: dark700.hex,
  buttonPrimaryBackground: dark400.hex,
  buttonPrimaryHover: dark500.hex,
  buttonPrimaryDisabledText: dark700.hex,
  buttonPrimaryDisabledBackground: grey200.hex,

  buttonSecondaryText: offBlack.hex,
  buttonSecondaryBackground: dark400.hex,
  buttonSecondaryHover: dark500.hex,
  buttonSecondaryDisabledText: dark500.hex,
  buttonSecondaryDisabledBackground: dark600.hex,

  buttonBrandText: offBlack.hex,
  buttonBrandBackground: purple300.hex,
  buttonBrandHover: purple500.hex,
  buttonBrandDisabledText: purple300.hex,
  buttonBrandDisabledBackground: purple600.hex,

  buttonDangerLight: red700.hex,
  buttonDangerHeavy: red500.hex,

  // hover ui buttons
  buttonHoverBackground: dark600.hex,
  buttonHoverBackgroundHover: dark500.hex,

  // dropline
  droplineBgColor: blue900.hex,
  droplineColor: blue600.hex,
  droplineGreyColor: purple600.hex,

  errorBlockColor: red50.hex,
  errorBlockWarning: orange700.hex,
  errorBlockAnnotationWarning: yellow700.hex,
  errorBlockError: red700.hex,

  errorPageGradientEnd: dark500.hex,

  mutationAnimationColor: yellow700.hex,

  currentTextColor: dark200.hex,

  linkNormalColor: malibu700.hex,
  linkNormalHoverColor: malibu700.hex,
  linkDangerColor: red500.hex,
  linkDangerHoverColor: red700.hex,

  bubbleColor: teal200.hex,
  bubbleBackground: teal800.hex,

  bubbleColumnSelectedColor: teal500.hex,
  bubbleColumnColor: dark600.hex,
  bubbleFormulaColor: dark600.hex,
  bubbleBackgroundColor: dark400.hex,

  bubbleColumnTextSelectedColor: dark600.hex,
  bubbleColumnTextColor: teal500.hex,
  bubbleFormulaTextColor: teal500.hex,
  bubbleTextColor: teal800.hex,

  variableHighlightColor: teal800.hex,
  variableHighlightTextColor: dark100.hex,

  bubbleTableFormulaColor: dark700.hex,
  bubbleTableFormulaTextColor: dark400.hex,

  selectionColor: blue700.hex,

  magicNumberTextColor: dark100.hex,

  tableSelectionBackgroundColor: blue700.hex,
  tableFocusColor: blue500.hex,
  tableFooterBackgroundColor: grey700.hex,

  tableLiveMakeHeaderButton: purple700.hex,
  tableLiveMakeHeaderButtonHover: purple600.hex,

  liveDataWeakBackgroundColor: purple900.hex,
  liveDataBackgroundColor: purple800.hex,
  liveDataTextColor: purple200.hex,

  liveDataIconStrokeColor: yellow500.hex,
  liveDataIconBgColor: yellow200.hex,
  liveDataIconDarkStrokeColor: yellow700.hex,
  liveDataIconAccentColor: yellow300.hex,

  importDataIconStrokeColor: orange500.hex,
  importDataIconBgColor: orange100.hex,
  importDataIconDarkStrokeColor: orange600.hex,
  importDataIconAccentColor: orange300.hex,

  // AI UI
  aiTextColor: teal500.hex,
  aiPanelBorderColor: dark500.hex,
  aiBubbleBackgroundColor: teal800.hex,
  aiSendButtonStrokeColor: teal100.hex,
  aiSendButtonBgColor: teal700.hex,
  aiSendButtonDisabledStrokeColor: dark500.hex,
  aiInsertButtonColor: dark200.hex,
  aiInsertButtonBgColor: dark500.hex,

  // chart themes
  chartThemeMonochromePurple1: purple600.hex,
  chartThemeMonochromePurple2: purple800.hex,
  chartThemeMonochromePurple3: purple500.hex,
  chartThemeMonochromePurple4: grey400.hex,
  chartThemeMonochromePurple5: purple700.hex,
  chartThemeMonochromePurple6: purple400.hex,
  chartThemeMonochromePurple7: purple200.hex,
  chartThemeMonochromePurple8: grey500.hex,
  chartThemeMonochromePurple9: grey600.hex,
  chartThemeMonochromePurple10: grey700.hex,
  chartThemeMonochromePurple11: purple300.hex,

  chartThemeMonochromeRed1: red600.hex,
  chartThemeMonochromeRed2: red800.hex,
  chartThemeMonochromeRed3: red500.hex,
  chartThemeMonochromeRed4: grey400.hex,
  chartThemeMonochromeRed5: red700.hex,
  chartThemeMonochromeRed6: red400.hex,
  chartThemeMonochromeRed7: red900.hex,
  chartThemeMonochromeRed8: grey500.hex,
  chartThemeMonochromeRed9: grey600.hex,
  chartThemeMonochromeRed10: grey700.hex,
  chartThemeMonochromeRed11: red300.hex,

  chartThemeMonochromeGrey1: grey400.hex,
  chartThemeMonochromeGrey2: grey600.hex,
  chartThemeMonochromeGrey3: grey500.hex,
  chartThemeMonochromeGrey4: grey300.hex,
  chartThemeMonochromeGrey5: grey700.hex,
  chartThemeMonochromeGrey6: grey200.hex,
  chartThemeMonochromeGrey7: grey400.hex,
  chartThemeMonochromeGrey8: grey600.hex,
  chartThemeMonochromeGrey9: grey500.hex,
  chartThemeMonochromeGrey10: grey300.hex,
  chartThemeMonochromeGrey11: grey700.hex,

  chartThemeMonochromeYellow1: yellow600.hex,
  chartThemeMonochromeYellow2: yellow800.hex,
  chartThemeMonochromeYellow3: yellow500.hex,
  chartThemeMonochromeYellow4: grey400.hex,
  chartThemeMonochromeYellow5: yellow700.hex,
  chartThemeMonochromeYellow6: yellow400.hex,
  chartThemeMonochromeYellow7: yellow900.hex,
  chartThemeMonochromeYellow8: grey500.hex,
  chartThemeMonochromeYellow9: grey600.hex,
  chartThemeMonochromeYellow10: grey700.hex,
  chartThemeMonochromeYellow11: yellow300.hex,

  chartThemeMonochromeBlue1: blue600.hex,
  chartThemeMonochromeBlue2: blue800.hex,
  chartThemeMonochromeBlue3: blue500.hex,
  chartThemeMonochromeBlue4: grey400.hex,
  chartThemeMonochromeBlue5: blue700.hex,
  chartThemeMonochromeBlue6: blue400.hex,
  chartThemeMonochromeBlue7: blue900.hex,
  chartThemeMonochromeBlue8: grey500.hex,
  chartThemeMonochromeBlue9: grey600.hex,
  chartThemeMonochromeBlue10: grey700.hex,
  chartThemeMonochromeBlue11: blue300.hex,

  chartThemeMonochromeGreen1: brand600.hex,
  chartThemeMonochromeGreen2: brand800.hex,
  chartThemeMonochromeGreen3: brand500.hex,
  chartThemeMonochromeGreen4: grey400.hex,
  chartThemeMonochromeGreen5: brand700.hex,
  chartThemeMonochromeGreen6: brand400.hex,
  chartThemeMonochromeGreen7: brand900.hex,
  chartThemeMonochromeGreen8: grey500.hex,
  chartThemeMonochromeGreen9: grey600.hex,
  chartThemeMonochromeGreen10: grey700.hex,
  chartThemeMonochromeGreen11: brand300.hex,

  chartThemeMonochromeOrange1: orange600.hex,
  chartThemeMonochromeOrange2: orange800.hex,
  chartThemeMonochromeOrange3: orange500.hex,
  chartThemeMonochromeOrange4: grey400.hex,
  chartThemeMonochromeOrange5: orange700.hex,
  chartThemeMonochromeOrange6: orange400.hex,
  chartThemeMonochromeOrange7: orange900.hex,
  chartThemeMonochromeOrange8: grey500.hex,
  chartThemeMonochromeOrange9: grey600.hex,
  chartThemeMonochromeOrange10: grey700.hex,
  chartThemeMonochromeOrange11: orange300.hex,

  chartThemeMulticolorPurple1: purple800.hex,
  chartThemeMulticolorPurple2: brand600.hex,
  chartThemeMulticolorPurple3: blue800.hex,
  chartThemeMulticolorPurple4: grey400.hex,
  chartThemeMulticolorPurple5: teal800.hex,
  chartThemeMulticolorPurple6: teal400.hex,
  chartThemeMulticolorPurple7: purple500.hex,
  chartThemeMulticolorPurple8: brand500.hex,
  chartThemeMulticolorPurple9: blue500.hex,
  chartThemeMulticolorPurple10: grey600.hex,
  chartThemeMulticolorPurple11: teal500.hex,

  chartThemeMulticolorRed1: red600.hex,
  chartThemeMulticolorRed2: purple800.hex,
  chartThemeMulticolorRed3: orange600.hex,
  chartThemeMulticolorRed4: blue600.hex,
  chartThemeMulticolorRed5: brand800.hex,
  chartThemeMulticolorRed6: grey400.hex,
  chartThemeMulticolorRed7: red800.hex,
  chartThemeMulticolorRed8: purple500.hex,
  chartThemeMulticolorRed9: orange800.hex,
  chartThemeMulticolorRed10: blue800.hex,
  chartThemeMulticolorRed11: brand800.hex,

  chartThemeMulticolorGrey1: grey400.hex,
  chartThemeMulticolorGrey2: grey600.hex,
  chartThemeMulticolorGrey3: teal800.hex,
  chartThemeMulticolorGrey4: teal500.hex,
  chartThemeMulticolorGrey5: grey700.hex,
  chartThemeMulticolorGrey6: teal900.hex,
  chartThemeMulticolorGrey7: grey500.hex,
  chartThemeMulticolorGrey8: teal600.hex,
  chartThemeMulticolorGrey9: grey200.hex,
  chartThemeMulticolorGrey10: teal400.hex,
  chartThemeMulticolorGrey11: grey400.hex,

  chartThemeMulticolorYellow1: yellow600.hex,
  chartThemeMulticolorYellow2: blue500.hex,
  chartThemeMulticolorYellow3: yellow800.hex,
  chartThemeMulticolorYellow4: grey400.hex,
  chartThemeMulticolorYellow5: blue800.hex,
  chartThemeMulticolorYellow6: grey600.hex,
  chartThemeMulticolorYellow7: yellow500.hex,
  chartThemeMulticolorYellow8: blue600.hex,
  chartThemeMulticolorYellow9: yellow700.hex,
  chartThemeMulticolorYellow10: grey500.hex,
  chartThemeMulticolorYellow11: blue700.hex,

  chartThemeMulticolorBlue1: blue600.hex,
  chartThemeMulticolorBlue2: purple800.hex,
  chartThemeMulticolorBlue3: grey400.hex,
  chartThemeMulticolorBlue4: teal800.hex,
  chartThemeMulticolorBlue5: teal500.hex,
  chartThemeMulticolorBlue6: teal600.hex,
  chartThemeMulticolorBlue7: blue800.hex,
  chartThemeMulticolorBlue8: purple500.hex,
  chartThemeMulticolorBlue9: grey600.hex,
  chartThemeMulticolorBlue10: teal400.hex,
  chartThemeMulticolorBlue11: teal900.hex,

  chartThemeMulticolorGreen1: brand500.hex,
  chartThemeMulticolorGreen2: teal800.hex,
  chartThemeMulticolorGreen3: grey400.hex,
  chartThemeMulticolorGreen4: brand400.hex,
  chartThemeMulticolorGreen5: teal500.hex,
  chartThemeMulticolorGreen6: blue700.hex,
  chartThemeMulticolorGreen7: teal400.hex,
  chartThemeMulticolorGreen8: grey600.hex,
  chartThemeMulticolorGreen9: brand900.hex,
  chartThemeMulticolorGreen10: teal800.hex,
  chartThemeMulticolorGreen11: brand800.hex,

  chartThemeMulticolorOrange1: orange600.hex,
  chartThemeMulticolorOrange2: yellow600.hex,
  chartThemeMulticolorOrange3: grey400.hex,
  chartThemeMulticolorOrange4: orange700.hex,
  chartThemeMulticolorOrange5: red500.hex,
  chartThemeMulticolorOrange6: red600.hex,
  chartThemeMulticolorOrange7: orange800.hex,
  chartThemeMulticolorOrange8: yellow500.hex,
  chartThemeMulticolorOrange9: grey600.hex,
  chartThemeMulticolorOrange10: orange500.hex,
  chartThemeMulticolorOrange11: red700.hex,
};
