import {
  blue100,
  blue200,
  blue300,
  blue400,
  blue50,
  blue500,
  blue600,
  blue700,
  brand100,
  brand200,
  brand300,
  brand400,
  brand500,
  brand600,
  brand700,
  grey100,
  grey200,
  grey300,
  grey400,
  grey50,
  grey500,
  grey600,
  grey700,
  offBlack,
  offWhite,
  orange100,
  orange200,
  orange300,
  orange400,
  orange50,
  orange500,
  orange600,
  orange700,
  purple100,
  purple200,
  purple300,
  purple400,
  purple50,
  purple500,
  purple700,
  red100,
  red200,
  red300,
  red400,
  red50,
  red500,
  red600,
  red700,
  teal100,
  teal200,
  teal300,
  teal50,
  teal500,
  teal600,
  teal700,
  teal800,
  white,
  yellow100,
  yellow200,
  yellow300,
  yellow400,
  yellow50,
  yellow500,
  yellow600,
  yellow700,
  yellow800,
} from '../color';
import { CssVariables } from '../CssVariables';

export const theme: CssVariables = {
  theme: 'light',
  toastOk: brand300.hex,
  toastDanger: red500.hex,
  toastWarning: yellow600.hex,

  cellDateSelected: brand300.hex,

  formulaUnitBackground: white.hex,
  thumbColor: white.hex,

  errorColor: red500.hex,
  errorColorLight: red100.hex,

  borderColor: grey200.hex,
  borderHighlightColor: grey300.hex,
  borderTable: grey200.hex,

  notebookStateDangerLight: red100.hex,
  notebookStateDangerHeavy: red300.hex,
  notebookStateWarningLight: orange100.hex,
  notebookStateWarningHeavy: orange500.hex,
  notebookStateOkLight: brand200.hex,
  notebookStateOkHeavy: brand600.hex,
  notebookStateDisabledLight: grey100.hex,
  notebookStateDisabledHeavy: grey600.hex,

  buttonDangerLight: red100.hex,
  buttonDangerHeavy: red300.hex,

  backgroundColor: white.hex,
  tintedBackgroundColor: grey50.hex,
  iconBackgroundColor: grey200.hex,
  offColor: offWhite.hex,
  spoilerColor: offBlack.hex,

  highlightColor: grey100.hex,
  strongHighlightColor: grey200.hex,
  strongerHighlightColor: grey300.hex,
  evenStrongerHighlightColor: grey400.hex,

  weakerTextColor: grey400.hex,
  weakTextColor: grey500.hex,
  normalTextColor: grey600.hex,
  strongTextColor: offBlack.hex,

  iconColorDark: offBlack.hex,
  iconColorLight: offWhite.hex,

  tooltipBackground: offBlack.hex,
  tooltipCodeBackground: grey300.hex,

  // used for other stuff, used to be slash commands
  weakerSlashIconColor: blue100.hex,
  weakSlashIconColor: blue200.hex,
  strongSlashIconColor: blue500.hex,

  // scrollbar color
  scrollbarColor: grey300.hex,

  // slash command default colors
  // overriden with setCssVar
  slashColorLight: grey200.hex,
  slashColorNormal: grey500.hex,
  slashColorHeavy: grey600.hex,

  slashColorOceanLight: blue100.hex,
  slashColorOceanNormal: blue200.hex,
  slashColorOceanHeavy: blue500.hex,

  slashColorMintLight: teal100.hex,
  slashColorMintNormal: teal200.hex,
  slashColorMintHeavy: teal500.hex,

  slashColorOrangeLight: orange100.hex,
  slashColorOrangeNormal: orange200.hex,
  slashColorOrangeHeavy: orange500.hex,

  slashColorWineLight: purple100.hex,
  slashColorWineNormal: purple200.hex,
  slashColorWineHeavy: purple500.hex,

  slashColorDaffodilLight: yellow200.hex,
  slashColorDaffodilNormal: yellow300.hex,
  slashColorDaffodilHeavy: yellow600.hex,

  // buttons
  buttonPrimaryText: white.hex,
  buttonPrimaryBackground: offBlack.hex,
  buttonPrimaryHover: grey600.hex,
  buttonPrimaryDisabledText: grey500.hex,
  buttonPrimaryDisabledBackground: offBlack.hex,

  buttonBrandText: offBlack.hex,
  buttonBrandBackground: brand500.hex,
  buttonBrandHover: brand300.hex,
  buttonBrandDisabledText: brand500.hex,
  buttonBrandDisabledBackground: brand200.hex,

  buttonSecondaryText: offBlack.hex,
  buttonSecondaryBackground: grey300.hex,
  buttonSecondaryHover: grey200.hex,
  buttonSecondaryDisabledText: grey500.hex,
  buttonSecondaryDisabledBackground: grey200.hex,

  // hover ui buttons
  buttonHoverBackground: grey200.hex,
  buttonHoverBackgroundHover: grey300.hex,

  errorBlockColor: orange700.hex,
  errorBlockWarning: orange50.hex,
  errorBlockInfo: grey100.hex,
  errorBlockAnnotationWarning: yellow100.hex,
  errorBlockError: red50.hex,

  errorPageGradientEnd: grey200.hex,

  mutationAnimationColor: yellow200.hex,

  currentTextColor: grey600.hex,

  linkNormalColor: blue700.hex,
  linkNormalHoverColor: blue700.hex,
  linkDangerColor: red500.hex,
  linkDangerHoverColor: red700.hex,

  selectionColor: grey300.hex,

  bubbleColor: teal800.hex,
  bubbleBackground: teal200.hex,

  // usage of variables Foo
  variableHighlightColor: grey200.hex,
  variableHighlightTextColor: grey600.hex,

  // columns of tables Table1.Dogs
  bubbleColumnSelectedColor: blue500.hex,
  bubbleColumnColor: blue50.hex,
  bubbleColumnTextSelectedColor: blue50.hex,
  bubbleColumnTextColor: blue500.hex,

  // formula definitions x = f + 1
  bubbleFormulaColor: teal200.hex,
  bubbleFormulaTextColor: teal800.hex,

  // formula definitions in tables
  bubbleTableFormulaColor: grey100.hex,
  bubbleTableFormulaTextColor: grey500.hex,

  // variables definition x = 1
  bubbleBackgroundColor: teal600.hex,
  bubbleTextColor: white.hex,

  magicNumberTextColor: teal600.hex,

  // dropline
  droplineBgColor: blue100.hex,
  droplineColor: blue300.hex,
  droplineGreyColor: grey300.hex,

  tableSelectionBackgroundColor: blue50.hex,
  tableFocusColor: blue300.hex,
  tableFooterBackgroundColor: grey100.hex,

  tableLiveMakeHeaderButton: blue200.hex,
  tableLiveMakeHeaderButtonHover: blue300.hex,

  liveDataWeakBackgroundColor: yellow300.hex,
  liveDataBackgroundColor: yellow400.hex,
  liveDataTextColor: yellow800.hex,

  liveDataIconStrokeColor: yellow500.hex,
  liveDataIconBgColor: yellow200.hex,
  liveDataIconDarkStrokeColor: yellow700.hex,
  liveDataIconAccentColor: yellow300.hex,

  importDataIconStrokeColor: orange500.hex,
  importDataIconBgColor: orange100.hex,
  importDataIconDarkStrokeColor: orange600.hex,
  importDataIconAccentColor: orange300.hex,

  // AI UI
  aiTextColor: teal600.hex,
  aiPanelBorderColor: grey300.hex,
  aiBubbleBackgroundColor: teal50.hex,
  aiSendButtonStrokeColor: teal600.hex,
  aiSendButtonBgColor: teal100.hex,
  aiFetchButtonBgColor: teal600.hex,
  aiFetchButtonDisabledBgColor: grey100.hex,
  aiSendButtonDisabledStrokeColor: grey400.hex,
  aiInsertButtonColor: grey600.hex,
  aiInsertButtonBgColor: grey100.hex,

  chartThemeMonochromePurple1: purple300.hex,
  chartThemeMonochromePurple2: purple200.hex,
  chartThemeMonochromePurple3: purple100.hex,
  chartThemeMonochromePurple4: grey300.hex,
  chartThemeMonochromePurple5: purple400.hex,
  chartThemeMonochromePurple6: purple500.hex,
  chartThemeMonochromePurple7: purple700.hex,
  chartThemeMonochromePurple8: grey400.hex,
  chartThemeMonochromePurple9: grey500.hex,
  chartThemeMonochromePurple10: grey200.hex,
  chartThemeMonochromePurple11: purple50.hex,

  chartThemeMonochromeRed1: red300.hex,
  chartThemeMonochromeRed2: red200.hex,
  chartThemeMonochromeRed3: red100.hex,
  chartThemeMonochromeRed4: grey300.hex,
  chartThemeMonochromeRed5: red400.hex,
  chartThemeMonochromeRed6: red500.hex,
  chartThemeMonochromeRed7: red700.hex,
  chartThemeMonochromeRed8: grey400.hex,
  chartThemeMonochromeRed9: grey500.hex,
  chartThemeMonochromeRed10: grey200.hex,
  chartThemeMonochromeRed11: red50.hex,

  chartThemeMonochromeGrey1: grey300.hex,
  chartThemeMonochromeGrey2: grey400.hex,
  chartThemeMonochromeGrey3: grey200.hex,
  chartThemeMonochromeGrey4: grey100.hex,
  chartThemeMonochromeGrey5: grey500.hex,
  chartThemeMonochromeGrey6: grey600.hex,
  chartThemeMonochromeGrey7: grey700.hex,
  chartThemeMonochromeGrey8: grey300.hex,
  chartThemeMonochromeGrey9: grey400.hex,
  chartThemeMonochromeGrey10: grey200.hex,
  chartThemeMonochromeGrey11: grey100.hex,

  chartThemeMonochromeYellow1: yellow300.hex,
  chartThemeMonochromeYellow2: yellow100.hex,
  chartThemeMonochromeYellow3: yellow200.hex,
  chartThemeMonochromeYellow4: grey200.hex,
  chartThemeMonochromeYellow5: yellow400.hex,
  chartThemeMonochromeYellow6: yellow600.hex,
  chartThemeMonochromeYellow7: yellow700.hex,
  chartThemeMonochromeYellow8: grey400.hex,
  chartThemeMonochromeYellow9: grey500.hex,
  chartThemeMonochromeYellow10: grey200.hex,
  chartThemeMonochromeYellow11: yellow50.hex,

  chartThemeMonochromeBlue1: blue300.hex,
  chartThemeMonochromeBlue2: blue200.hex,
  chartThemeMonochromeBlue3: blue100.hex,
  chartThemeMonochromeBlue4: grey200.hex,
  chartThemeMonochromeBlue5: blue400.hex,
  chartThemeMonochromeBlue6: blue500.hex,
  chartThemeMonochromeBlue7: blue600.hex,
  chartThemeMonochromeBlue8: grey400.hex,
  chartThemeMonochromeBlue9: grey500.hex,
  chartThemeMonochromeBlue10: grey200.hex,
  chartThemeMonochromeBlue11: blue50.hex,

  chartThemeMonochromeGreen1: brand400.hex,
  chartThemeMonochromeGreen2: brand200.hex,
  chartThemeMonochromeGreen3: brand300.hex,
  chartThemeMonochromeGreen4: grey200.hex,
  chartThemeMonochromeGreen5: brand500.hex,
  chartThemeMonochromeGreen6: brand600.hex,
  chartThemeMonochromeGreen7: brand700.hex,
  chartThemeMonochromeGreen8: grey400.hex,
  chartThemeMonochromeGreen9: grey500.hex,
  chartThemeMonochromeGreen10: grey200.hex,
  chartThemeMonochromeGreen11: brand100.hex,

  chartThemeMonochromeOrange1: orange300.hex,
  chartThemeMonochromeOrange2: orange200.hex,
  chartThemeMonochromeOrange3: orange100.hex,
  chartThemeMonochromeOrange4: grey200.hex,
  chartThemeMonochromeOrange5: orange400.hex,
  chartThemeMonochromeOrange6: orange500.hex,
  chartThemeMonochromeOrange7: orange700.hex,
  chartThemeMonochromeOrange8: grey400.hex,
  chartThemeMonochromeOrange9: grey500.hex,
  chartThemeMonochromeOrange10: grey200.hex,
  chartThemeMonochromeOrange11: orange50.hex,

  chartThemeMulticolorPurple1: purple200.hex,
  chartThemeMulticolorPurple2: brand400.hex,
  chartThemeMulticolorPurple3: blue200.hex,
  chartThemeMulticolorPurple4: grey300.hex,
  chartThemeMulticolorPurple5: teal200.hex,
  chartThemeMulticolorPurple6: teal700.hex,
  chartThemeMulticolorPurple7: purple100.hex,
  chartThemeMulticolorPurple8: brand300.hex,
  chartThemeMulticolorPurple9: blue300.hex,
  chartThemeMulticolorPurple10: grey400.hex,
  chartThemeMulticolorPurple11: teal100.hex,

  chartThemeMulticolorRed1: red300.hex,
  chartThemeMulticolorRed2: purple200.hex,
  chartThemeMulticolorRed3: orange300.hex,
  chartThemeMulticolorRed4: blue300.hex,
  chartThemeMulticolorRed5: brand200.hex,
  chartThemeMulticolorRed6: grey300.hex,
  chartThemeMulticolorRed7: red200.hex,
  chartThemeMulticolorRed8: purple100.hex,
  chartThemeMulticolorRed9: orange200.hex,
  chartThemeMulticolorRed10: blue300.hex,
  chartThemeMulticolorRed11: brand200.hex,

  chartThemeMulticolorGrey1: grey300.hex,
  chartThemeMulticolorGrey2: grey400.hex,
  chartThemeMulticolorGrey3: teal200.hex,
  chartThemeMulticolorGrey4: teal100.hex,
  chartThemeMulticolorGrey5: grey500.hex,
  chartThemeMulticolorGrey6: teal600.hex,
  chartThemeMulticolorGrey7: grey200.hex,
  chartThemeMulticolorGrey8: teal300.hex,
  chartThemeMulticolorGrey9: grey600.hex,
  chartThemeMulticolorGrey10: teal700.hex,
  chartThemeMulticolorGrey11: grey700.hex,

  chartThemeMulticolorYellow1: yellow300.hex,
  chartThemeMulticolorYellow2: blue200.hex,
  chartThemeMulticolorYellow3: grey300.hex,
  chartThemeMulticolorYellow4: purple100.hex,
  chartThemeMulticolorYellow5: red100.hex,
  chartThemeMulticolorYellow6: yellow200.hex,
  chartThemeMulticolorYellow7: orange200.hex,
  chartThemeMulticolorYellow8: grey400.hex,
  chartThemeMulticolorYellow9: blue300.hex,
  chartThemeMulticolorYellow10: purple200.hex,
  chartThemeMulticolorYellow11: red200.hex,

  chartThemeMulticolorBlue1: blue300.hex,
  chartThemeMulticolorBlue2: purple200.hex,
  chartThemeMulticolorBlue3: grey300.hex,
  chartThemeMulticolorBlue4: teal200.hex,
  chartThemeMulticolorBlue5: teal100.hex,
  chartThemeMulticolorBlue6: teal700.hex,
  chartThemeMulticolorBlue7: blue200.hex,
  chartThemeMulticolorBlue8: purple100.hex,
  chartThemeMulticolorBlue9: grey400.hex,
  chartThemeMulticolorBlue10: teal300.hex,
  chartThemeMulticolorBlue11: teal600.hex,

  chartThemeMulticolorGreen1: brand300.hex,
  chartThemeMulticolorGreen2: teal200.hex,
  chartThemeMulticolorGreen3: grey300.hex,
  chartThemeMulticolorGreen4: brand600.hex,
  chartThemeMulticolorGreen5: teal100.hex,
  chartThemeMulticolorGreen6: brand500.hex,
  chartThemeMulticolorGreen7: teal700.hex,
  chartThemeMulticolorGreen8: grey400.hex,
  chartThemeMulticolorGreen9: brand700.hex,
  chartThemeMulticolorGreen10: teal200.hex,
  chartThemeMulticolorGreen11: brand200.hex,

  chartThemeMulticolorOrange1: orange300.hex,
  chartThemeMulticolorOrange2: yellow300.hex,
  chartThemeMulticolorOrange3: grey300.hex,
  chartThemeMulticolorOrange4: orange400.hex,
  chartThemeMulticolorOrange5: red100.hex,
  chartThemeMulticolorOrange6: red300.hex,
  chartThemeMulticolorOrange7: orange200.hex,
  chartThemeMulticolorOrange8: yellow200.hex,
  chartThemeMulticolorOrange9: grey400.hex,
  chartThemeMulticolorOrange10: orange600.hex,
  chartThemeMulticolorOrange11: red600.hex,
};
