name: Collect Garbage Stacks
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '1 1 * * *'

jobs:
  removestacks:
    name: Remove garbage stacks
    timeout-minutes: 90
    runs-on: ubuntu-latest
    concurrency:
      group: collect-garbage-stacks
      cancel-in-progress: false
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@3d21ddcb5087c3d29b7e19fe293e3455fabe32af # v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Cache Yarn dependencies and Node modules
        uses: buildjet/cache@3e70d19e31d6a8030aeddf6ed8dbe601f94d09f4 # v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'

      - name: Uses wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0
        with:
          version: 'latest'

      - name: Check if node_modules is cached
        id: cache-check
        run: |
          if [ -d "node_modules" ]; then
            echo "restored=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'
          DECI_IMAGE_LAMBDA_LAYER: 'arn:aws:lambda:eu-west-2:861969788890:layer:sharp:2'
        run: yarn install --ignore-engines

      - name: Collect stacks
        run: ./scripts/aws-garbage-collect-stacks.sh

      - name: Collect log groups
        run: ./scripts/aws-garbage-collect-dev-log-groups.sh
