name: Deploy Discord Customer Support Bot

on:
  workflow_run:
    workflows: ['Deploy Prod']
    types:
      - completed

jobs:
  deploy-bot:
    # DISABLED: Product discontinued, open-sourcing codebase
    if: false
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-discord-customer-support-bot
      cancel-in-progress: true
    steps:
      #### Prepare

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Uses wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0
        with:
          version: 'latest'

      - name: Install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'
        run: yarn install --ignore-engines

      - name: Cache NX things
        id: node-modules-nx-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            node_modules/.cache
            dist
          key: nx-node-modules-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nx-node-modules-cache-

      #### Deploy

      - name: Deploy Discord Bot
        env:
          DISCORD_APP_ID: '${{secrets.DISCORD_APP_ID}}'
          DISCORD_BOT_TOKEN: '${{secrets.DISCORD_BOT_TOKEN}}'
        run: |
          yarn deploy:discord-customer-support-bot
