name: Deploy PR

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches-ignore: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Find PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Deploy
        run: "npm run deploy:pr -- ${{steps.findPr.outputs.number}}"

      - name: Commit Cloudformation
        uses: EndBug/add-and-commit@v7
        with:
          add: 'apps/backend/sam.*'
          message: 'new cloudformation after deploy'

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - deploy
    steps:
    - name: Find PR
      uses: jwalton/gh-find-current-pr@v1
      id: findPr
    - name: Notify
      uses: nobrayner/discord-webhook@v1
      with:
        github-token: ${{ secrets.github_token }}
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Deployment of PR ${{steps.findPr.outputs.number}} {{STATUS}}"

