name: Deploy Prod

on:
  release:
    types: ['published']

jobs:
  deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: deploy-prod
      cancel-in-progress: false
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'
        run: yarn install --ignore-engines

      - name: Cache NX things
        id: node-modules-nx-cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.cache
            dist
          key: nx-node-modules-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nx-node-modules-cache-

      - name: Deploy
        env:
          DEPLOY_NAME: 'alpha'
          DEBUG: '@decipad/*'
          NODE_ENV: 'production'
          DECI_ZONE_ID: '${{secrets.DECI_ZONE_ID}}'
          DECI_CERTIFICATE_ARN: '${{secrets.DECI_ALPHA_CERTIFICATE_ARN}}'
          SENTRY_DSN: '${{secrets.SENTRY_DSN}}'
          SENTRY_ORG: '${{secrets.SENTRY_ORG}}'
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_ENVIRONMENT: alpha
          NEXTAUTH_URL: 'https://app.decipad.com/api/auth'
          GITHUB_CLIENT_ID: '${{secrets.DECI_ALPHA_GITHUB_CLIENT_ID}}'
          GITHUB_CLIENT_SECRET: '${{secrets.DECI_ALPHA_GITHUB_CLIENT_SECRET}}'
          JWT_SECRET: '${{secrets.ALPHA_JWT_SECRET}}'
          OPENAI_API_KEY: '${{secrets.OPENAI_API_KEY}}'
          DECI_SES_ACCESS_KEY_ID: '${{secrets.DECI_SES_ACCESS_KEY_ID}}'
          DECI_SES_SECRET_ACCESS_KEY: '${{secrets.DECI_SES_SECRET_ACCESS_KEY}}'
          DECI_INVITE_EXPIRATION_SECONDS: '${{secrets.DECI_INVITE_EXPIRATION_SECONDS}}'
          DECI_KEY_VALIDATION_EXPIRATION_SECONDS: '${{secrets.DECI_KEY_VALIDATION_EXPIRATION_SECONDS}}'
          DECI_FROM_EMAIL_ADDRESS: '${{secrets.DECI_FROM_EMAIL_ADDRESS}}'
          DECI_APP_URL_BASE: 'https://app.decipad.com'
          DECI_S3_ENDPOINT: 's3.eu-west-2.amazonaws.com'
          DECI_S3_ACCESS_KEY_ID: '${{secrets.DECI_S3_ACCESS_KEY_ID}}'
          DECI_S3_SECRET_ACCESS_KEY: '${{secrets.DECI_S3_SECRET_ACCESS_KEY}}'
          DECI_S3_PADS_BUCKET: '${{secrets.DECI_S3_PADS_BUCKET}}'
          DECI_S3_ATTACHMENTS_BUCKET: '${{secrets.ALPHA_DECI_S3_ATTACHMENTS_BUCKET}}'
          DECI_GOOGLESHEETS_API_KEY: '${{secrets.ALPHA_DECI_GOOGLESHEETS_API_KEY}}'
          DECI_GOOGLESHEETS_CLIENT_ID: '${{secrets.ALPHA_DECI_GOOGLESHEETS_CLIENT_ID}}'
          DECI_GOOGLESHEETS_CLIENT_SECRET: '${{secrets.ALPHA_DECI_GOOGLESHEETS_CLIENT_SECRET}}'
          DISCORD_PUBLIC_KEY: '${{secrets.DISCORD_PUBLIC_KEY}}'
          DISCORD_APP_ID: '${{secrets.DISCORD_APP_ID}}'
          REACT_APP_HOTJAR_SITE_ID: '${{secrets.ALPHA_HOTJAR_SITE_ID}}'
          REACT_APP_ANALYTICS_WRITE_KEY: '${{secrets.ALPHA_ANALYTICS_WRITE_KEY}}'
          REACT_APP_INTERCOM_APP_ID: '${{secrets.ALPHA_INTERCOM_APP_ID}}'
          INTERCOM_SECRET_ID: '${{secrets.ALPHA_INTERCOM_SECRET_ID}}'
          STRIPE_API_KEY: '${{secrets.ALPHA_STRIPE_API_KEY}}'
          STRIPE_WEBHOOK_SECRET: '${{secrets.ALPHA_STRIPE_WEBHOOK_SECRET}}'
          NODE_OPTIONS: '--enable-source-maps --max_old_space_size=16384'
          GIT_COMMIT_HASH: '${{github.sha}}'

        run: |
          export SAM_LOCATION="s3://decipad-backend-sam/alpha.decipad.com"
          scripts/pull-sam.sh

          cd apps/backend
          export PATH=./node_modules/.bin:$PATH
          arc env staging NODE_OPTIONS --enable-source-maps --max_old_space_size=16384
          cd ../..

          yarn deploy:prod
          scripts/push-sam.sh
