name: Sentry Release

on:
  push:
    branches: [main]

jobs:
  index:
    runs-on: ubuntu-latest
    concurrency:
      group: sentry-release-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - name: Get the Decipad Repo
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set NPM Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: npm-and-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-and-cypress-

      - name: Install Dependencies
        run: yarn install

      - name: Create Source Maps
        run: scripts/build-source-maps.sh

      - uses: actions/checkout@v2
      - name: Upload Sourcemaps to Sentry
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: staging
          sourcemaps: 'dist/sourcemaps/'

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - index
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          title: 'Sourcemaps'
          description: 'Sourcemaps uploaded to sentry'
          avatar-url: 'https://singlecolorimage.com/get/d2ec7b/100x100'
          include-details: false
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
