name: Sentry Release

on:
  workflow_run:
    workflows: ['Deploy']
    branches: [main]
    types:
      - completed

jobs:
  index:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    concurrency:
      group: sentry-release-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: development
          sourcemaps: './apps/clients/src, ./libs/config/src, ./libs/editor/src, ./libs/graphqlserver/src, ./libs/services/src'

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - index
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
