name: 🔬 Run Production Regression Tests

on:
  workflow_run:
    workflows: ['Deploy Prod']
    types:
      - completed

jobs:
  build:
    name: 🔬 Run Regression Tests in Production
    timeout-minutes: 25
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Uses wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Use Node.js
        uses: buildjet/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --ignore-engines --ignore=apps/docs

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run e2e Regression Tests
        env:
          NODE_OPTIONS: '--enable-source-maps --max_old_space_size=16384'
          VITE_STRIPE_CUSTOMER_PORTAL_LINK: '${{vars.DEV_STRIPE_CUSTOMER_PORTAL_LINK}}'
          TESTMAIL_APIKEY: '${{secrets.TESTMAIL_APIKEY}}'
          TESTMAIL_NAMESPACE: '${{secrets.TESTMAIL_NAMESPACE}}'
          USER_AGENT_KEY: '${{secrets.USER_AGENT_KEY}}'
          GOOGLE_BIGQUERY_CREDENTIALS: '${{secrets.GOOGLE_BIGQUERY_CREDENTIALS}}'
          DECI_VERBOSE: false
        run: ./scripts/e2e-regression.sh

      - uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: playwright-report
          path: /home/runner/actions-runner/_work/decipad/decipad/playwright-report
          retention-days: 3

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ failure() && github.ref == 'refs/heads/main' }}

    steps:
      - name: Notify
        uses: decipad/discord-webhook@v5
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
