name: 🔬 Run Smoke Tests

on:
  push:
    # Since Percy will auto-approve main, it'll become the new baseline for
    # future PRs.
    branches: [main]
    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'

jobs:
  build:
    name: 🔬 Run Smoke Tests
    timeout-minutes: 25
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: buildjet/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --ignore-engines --ignore=apps/docs

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Build Back-End
        run: yarn build:backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run e2e & Visual Regression Tests
        env:
          PERCY_TOKEN: '${{ secrets.PERCY_TOKEN }}'
          NODE_OPTIONS: '--enable-source-maps --max_old_space_size=16384'
          REACT_APP_STRIPE_PAYMENT_LINK: '${{secrets.DEV_STRIPE_PAYMENT_LINK}}'
          REACT_APP_STRIPE_CUSTOMER_PORTAL_LINK: '${{secrets.DEV_STRIPE_CUSTOMER_PORTAL_LINK}}'
          DECI_VERBOSE: false
        run: ./scripts/e2e-noshard.sh

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: /home/runner/actions-runner/_work/decipad/decipad/playwright-report
          retention-days: 3

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ failure() && github.ref == 'refs/heads/main' }}

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
