name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm cache
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.cache
        key: npm-and-cypress-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-and-cypress-

    - run: npm ci

    - name: Cache NX things
      id: node-modules-nx-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules/.cache
          dist
        key: nx-node-modules-cache-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          nx-node-modules-cache-

    - run: npm run lint
    - run: npm run typecheck
    - run: npm run test:coverage

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ failure() }} # You always want to be notified: success, failure, or cancelled

    steps:
    - name: Notify
      uses: nobrayner/discord-webhook@v1
      with:
        github-token: ${{ secrets.github_token }}
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
