name: 🔬 Run E2E Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'

env:
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  build:
    name: 🔬 Run e2e Tests
    timeout-minutes: 60
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: e2e-${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1

      - name: Cache Yarn dependencies and Node modules
        uses: buildjet/cache@3e70d19e31d6a8030aeddf6ed8dbe601f94d09f4 # v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-24.x-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-24.x-
            ${{ runner.os }}-yarn-

      - name: Use Node.js
        uses: buildjet/setup-node@6131e76b005f1e3f5c721e0ca2d8279eb577c3a8 # v4
        with:
          node-version: 24.x

      - name: Uses wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0
        with:
          version: 'latest'

      - name: Install dependencies
        run: yarn install --ignore-engines --ignore=apps/docs

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(node -p "require('@playwright/test/package.json').version")
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: buildjet/cache@3e70d19e31d6a8030aeddf6ed8dbe601f94d09f4 # v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Build Back-End
        run: yarn build:backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run e2e
        env:
          NODE_OPTIONS: '--enable-source-maps --max_old_space_size=16384'
          STRIPE_EXTRA_CREDITS_PRODUCT_ID: '${{secrets.DEV_STRIPE_EXTRA_CREDITS_PRODUCT_ID}}'
          STRIPE_SUBSCRIPTIONS_PRODUCT_ID: '${{secrets.DEV_STRIPE_SUBSCRIPTIONS_PRODUCT_ID}}'
          VITE_STRIPE_CUSTOMER_PORTAL_LINK: '${{vars.DEV_STRIPE_CUSTOMER_PORTAL_LINK}}'
          VITE_STRIPE_API_KEY: '${{secrets.DEV_STRIPE_API_KEY}}'
          VITE_GOOGLESHEETS_API_KEY: '${{secrets.DECI_GOOGLESHEETS_API_KEY}}'
          GOOGLE_BIGQUERY_CREDENTIALS: '${{secrets.GOOGLE_BIGQUERY_CREDENTIALS}}'
          DECI_VERBOSE: true
          TEST_DATABASE: '${{secrets.TEST_DATABASE}}'
        run: ./scripts/e2e.sh

      - name: Upload Blob Report to GitHub Actions Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: all-blob-reports
          path: /home/runner/actions-runner/_work/decipad/decipad/blob-report
          retention-days: 1

  merge-reports:
    name: 📋 Create Report
    if: failure()
    needs: [build]

    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: report-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Cache Yarn dependencies and Node modules
        uses: buildjet/cache@3e70d19e31d6a8030aeddf6ed8dbe601f94d09f4 # v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-24.x-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-24.x-
            ${{ runner.os }}-yarn-

      - uses: buildjet/setup-node@6131e76b005f1e3f5c721e0ca2d8279eb577c3a8 # v4
        with:
          node-version: 24.x

      - name: Install dependencies
        run: yarn install --ignore-engines --ignore=apps/docs

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: all-blob-reports
          path: all-blob-reports

      - name: Merge GitHub Report
        run: npx playwright merge-reports --reporter github ./all-blob-reports

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 5

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: [build]
    if: false

    steps:
      - name: Notify
        uses: decipad/discord-webhook@4d1e357ee56442b97220c62f5f17a3e05a515291 # v5
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
