name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm cache
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.cache
        key: npm-and-cypress-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-and-cypress-

    - run: npm ci

    - name: Cache NX things
      id: node-modules-nx-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules/.cache
          dist
        key: nx-node-modules-cache-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          nx-node-modules-cache-

    - run: npm run lint
    - run: npm run typecheck

    - name: Run tests
      run: npm run test:coverage
      env:
        JWT_SECRET: "23eqhjdskajhaskjcatwndasjkdn0alklrjqwr92309e"
        JWT_SIGNING_PRIVATE_KEY: '{"kty":"oct","kid":"ZOZrs3wZ9G2ANQMc2H74fvZK9g50dBdFuCrECQwbznM","alg":"HS512","k":"JbdHYPsSYiiHDabJZTo1VUJd8HF56eCM_4LTbncw8Wg"}'
        DECI_INVITE_EXPIRATION_SECONDS: "604800"
        DECI_KEY_VALIDATION_EXPIRATION_SECONDS: "2592000"

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ failure() }}

    steps:
    - name: Notify
      uses: nobrayner/discord-webhook@v1
      with:
        github-token: ${{ secrets.github_token }}
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
