name: 🔬 Run E2E Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'

env:
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  build:
    name: 🔬 Run e2e Tests
    timeout-minutes: 60
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: e2e-${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }} - ${{ matrix.shard }}
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [18.x]
        shard: [1, 2]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Yarn dependencies and Node modules
        uses: buildjet/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Uses wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: buildjet/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if node_modules is cached
        id: cache-check
        run: |
          if [ -d "node_modules" ]; then
            echo "restored=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Dependencies
        run: yarn install --ignore-engines --ignore=apps/docs

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(node -p "require('@playwright/test/package.json').version")
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: buildjet/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Build Back-End
        run: yarn build:backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run e2e & Visual Regression Tests (${{ matrix.shard }}/${{ strategy.job-total }})
        env:
          PERCY_TOKEN: '${{ secrets.PERCY_TOKEN }}'
          NODE_OPTIONS: '--enable-source-maps --max_old_space_size=16384'
          STRIPE_EXTRA_CREDITS_PRODUCT_ID: '${{secrets.DEV_STRIPE_EXTRA_CREDITS_PRODUCT_ID}}'
          STRIPE_SUBSCRIPTIONS_PRODUCT_ID: '${{secrets.DEV_STRIPE_SUBSCRIPTIONS_PRODUCT_ID}}'
          VITE_STRIPE_CUSTOMER_PORTAL_LINK: '${{vars.DEV_STRIPE_CUSTOMER_PORTAL_LINK}}'
          VITE_STRIPE_API_KEY: '${{secrets.DEV_STRIPE_API_KEY}}'
          DECI_VERBOSE: true
          PERCY_PARALLEL_TOTAL: 2
          TEST_DATABASE: '${{secrets.TEST_DATABASE}}'
        run: ./scripts/e2e.sh ${{ matrix.shard }} ${{ strategy.job-total }}

      - name: Upload Blob Report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: all-blob-reports
          path: /home/runner/actions-runner/_work/decipad/decipad/blob-report
          retention-days: 1

      - name: Finalize Percy
        env:
          PERCY_TOKEN: '${{ secrets.PERCY_TOKEN }}'
        if: failure() || cancelled()
        run: npx percy build:finalize

  merge-reports:
    name: 📋 Create Report
    if: failure()
    needs: [build]

    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: report-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Cache Yarn dependencies and Node modules
        uses: buildjet/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - uses: buildjet/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if node_modules is cached
        id: cache-check
        run: |
          if [ -d "node_modules" ]; then
            echo "restored=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Dependencies
        run: yarn install --ignore-engines --ignore=apps/docs
        if: steps.cache-check.outputs.restored != 'true'

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-blob-reports
          path: all-blob-reports

      - name: Merge GitHub Report
        run: npx playwright merge-reports --reporter github ./all-blob-reports

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 5

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}

    steps:
      - name: Notify
        uses: decipad/discord-webhook@v5
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
