name: Run E2E Tests

on:
  push:
    # Since Percy will auto-approve main, it'll become the new baseline for
    # future PRs.
    branches: [main]
    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - '.yarn/**'
      - 'apps/docs/**'

jobs:
  build:
    timeout-minutes: 60
    runs-on: buildjet-4vcpu-ubuntu-2204

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        shard: [1, 2]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install
        run: yarn install --ignore-engines

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run end-to-end and visual regression tests (${{ matrix.shard }}/${{ strategy.job-total }})
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          PERCY_TOKEN: '${{ secrets.PERCY_TOKEN }}'
        run: ./scripts/e2e.sh ${{ matrix.shard }} ${{ strategy.job-total }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: /home/runner/actions-runner/_work/decipad/decipad/playwright-report
          retention-days: 7

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ failure() && github.ref == 'refs/heads/main' }}

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
