name: Undeploy PR

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: npm-and-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-and-cypress-

      - name: Install
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Undeploy
        run: |
          export SAM_LOCATION="s3://decipad-backend-sam/${{ github.event.pull_request.number }}.dev.decipad.com"

          npm run undeploy:pr -- --app decipad-backend --name ${{ github.event.pull_request.number }} --force
          scripts/destroy-sam.sh

  #### Notify

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - undeploy
    steps:
      - name: Notify
        if: ${{ failure() }}
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'Removal of PR ${{github.event.pull_request.number}} deployment : {{STATUS}}'
          include-details: true
