name: Undeploy PR

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  undeploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-stack
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Cache yarn
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install
        run: yarn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Undeploy
        run: |
          export SAM_LOCATION="s3://decipad-backend-sam/${{ github.event.pull_request.number }}.dev.decipad.com"

          yarn undeploy:pr --app decipad-backend --name ${{ github.event.pull_request.number }} --force
          scripts/destroy-sam.sh

  #### Notify

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - undeploy
    steps:
      - name: Notify
        if: ${{ failure() }}
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'Removal of PR ${{github.event.pull_request.number}} deployment : {{STATUS}}'
          include-details: true
