name: Undeploy PR

on:
  pull_request:
    types: [closed]

jobs:
  undeploy:
    # DISABLED: Product discontinued, open-sourcing codebase
    if: false
    runs-on: ubuntu-latest
    concurrency:
      group: 'deploy-pr-${{ github.event.pull_request.number }}'
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
          cache: yarn

      - name: Uses wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0
        with:
          version: 'latest'

      - name: Install dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'
        run: yarn install --ignore-engines

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@3d21ddcb5087c3d29b7e19fe293e3455fabe32af # v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Undeploy
        run: |
          export SAM_BUCKET="decipad-dev-backend-sam"
          export SAM_LOCATION="s3://decipad-dev-backend-sam/${{ github.event.pull_request.number }}.decipadstaging.com"

          ./scripts/aws-delete-stack.sh ${{ github.event.pull_request.number }}
          ./scripts/aws-delete-parameters.sh DecipadBackendStaging${{ github.event.pull_request.number }}
          scripts/destroy-sam.sh

  #### Notify

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - undeploy
    steps:
      - name: Notify
        if: ${{ failure() }}
        uses: decipad/discord-webhook@4d1e357ee56442b97220c62f5f17a3e05a515291 # v5
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'Removal of PR ${{github.event.pull_request.number}} deployment : {{STATUS}}'
          include-details: true
